// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: services.proto
// Protobuf C++ Version: 7.34.1

#include "services.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace secure_lab {

inline constexpr ValidationResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        is_valid_{false} {}

template <typename>
constexpr ValidationResponse::ValidationResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ValidationResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct ValidationResponseDefaultTypeInternal {
  constexpr ValidationResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ValidationResponseDefaultTypeInternal() {}
  union {
    ValidationResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ValidationResponseDefaultTypeInternal _ValidationResponse_default_instance_;

inline constexpr UserReport::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        fav_color_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        is_authenticated_{false},
        fav_number_{0} {}

template <typename>
constexpr UserReport::UserReport(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(UserReport_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct UserReportDefaultTypeInternal {
  constexpr UserReportDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UserReportDefaultTypeInternal() {}
  union {
    UserReport _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UserReportDefaultTypeInternal _UserReport_default_instance_;

inline constexpr UserPreferences::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        fav_color_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        fav_number_{0} {}

template <typename>
constexpr UserPreferences::UserPreferences(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(UserPreferences_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct UserPreferencesDefaultTypeInternal {
  constexpr UserPreferencesDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UserPreferencesDefaultTypeInternal() {}
  union {
    UserPreferences _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UserPreferencesDefaultTypeInternal _UserPreferences_default_instance_;

inline constexpr Name::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
constexpr Name::Name(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Name_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct NameDefaultTypeInternal {
  constexpr NameDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NameDefaultTypeInternal() {}
  union {
    Name _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NameDefaultTypeInternal _Name_default_instance_;
}  // namespace secure_lab
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_services_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_services_2eproto = nullptr;
const ::uint32_t
    TableStruct_services_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::secure_lab::Name, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::secure_lab::Name, _impl_.name_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::secure_lab::ValidationResponse, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::secure_lab::ValidationResponse, _impl_.is_valid_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::secure_lab::UserPreferences, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::secure_lab::UserPreferences, _impl_.fav_color_),
        PROTOBUF_FIELD_OFFSET(::secure_lab::UserPreferences, _impl_.fav_number_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::secure_lab::UserReport, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::secure_lab::UserReport, _impl_.is_authenticated_),
        PROTOBUF_FIELD_OFFSET(::secure_lab::UserReport, _impl_.fav_color_),
        PROTOBUF_FIELD_OFFSET(::secure_lab::UserReport, _impl_.fav_number_),
        1,
        0,
        2,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::secure_lab::Name)},
        {5, sizeof(::secure_lab::ValidationResponse)},
        {10, sizeof(::secure_lab::UserPreferences)},
        {17, sizeof(::secure_lab::UserReport)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::secure_lab::_Name_default_instance_._instance,
    &::secure_lab::_ValidationResponse_default_instance_._instance,
    &::secure_lab::_UserPreferences_default_instance_._instance,
    &::secure_lab::_UserReport_default_instance_._instance,
};
const char descriptor_table_protodef_services_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\016services.proto\022\nsecure_lab\"\024\n\004Name\022\014\n\004"
    "name\030\001 \001(\t\"&\n\022ValidationResponse\022\020\n\010is_v"
    "alid\030\001 \001(\010\"8\n\017UserPreferences\022\021\n\tfav_col"
    "or\030\001 \001(\t\022\022\n\nfav_number\030\002 \001(\005\"M\n\nUserRepo"
    "rt\022\030\n\020is_authenticated\030\001 \001(\010\022\021\n\tfav_colo"
    "r\030\002 \001(\t\022\022\n\nfav_number\030\003 \001(\0052N\n\014Orchestra"
    "tor\022>\n\022ExecuteAccessCheck\022\020.secure_lab.N"
    "ame\032\026.secure_lab.UserReport2M\n\tValidator"
    "\022@\n\014ValidateUser\022\020.secure_lab.Name\032\036.sec"
    "ure_lab.ValidationResponse2S\n\022Preference"
    "sService\022=\n\014GetUserStats\022\020.secure_lab.Na"
    "me\032\033.secure_lab.UserPreferencesb\006proto3"
};
static ::absl::once_flag descriptor_table_services_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_services_2eproto = {
    false,
    false,
    479,
    descriptor_table_protodef_services_2eproto,
    "services.proto",
    &descriptor_table_services_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_services_2eproto::offsets,
    file_level_enum_descriptors_services_2eproto,
    file_level_service_descriptors_services_2eproto,
};
namespace secure_lab {
// ===================================================================

class Name::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Name>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Name, _impl_._has_bits_);
};

Name::Name(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Name_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:secure_lab.Name)
}
PROTOBUF_NDEBUG_INLINE Name::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::secure_lab::Name& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        name_(arena, from.name_) {}

Name::Name(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Name& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Name_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Name* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:secure_lab.Name)
}
PROTOBUF_NDEBUG_INLINE Name::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        name_(arena) {}

inline void Name::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Name::~Name() {
  // @@protoc_insertion_point(destructor:secure_lab.Name)
  SharedDtor(*this);
}
inline void Name::SharedDtor(MessageLite& self) {
  Name& this_ = static_cast<Name&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.name_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Name::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Name(arena);
}
constexpr auto Name::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Name),
                                            alignof(Name));
}
constexpr auto Name::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Name_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &Name::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Name>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Name::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Name>(), &Name::ByteSizeLong,
              &Name::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Name, _impl_._cached_size_),
          false,
      },
      &Name::kDescriptorMethods,
      &descriptor_table_services_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Name_class_data_ =
        Name::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Name::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Name_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Name_class_data_.tc_table);
  return Name_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 28, 2>
Name::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Name, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    Name_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::secure_lab::Name>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(Name, _impl_.name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(Name, _impl_.name_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\17\4\0\0\0\0\0\0"
    "secure_lab.Name"
    "name"
  }},
};
PROTOBUF_NOINLINE void Name::Clear() {
// @@protoc_insertion_point(message_clear_start:secure_lab.Name)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.name_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Name::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Name& this_ = static_cast<const Name&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Name::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Name& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:secure_lab.Name)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string name = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_name().empty()) {
      const ::std::string& _s = this_._internal_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "secure_lab.Name.name");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:secure_lab.Name)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Name::ByteSizeLong(const MessageLite& base) {
  const Name& this_ = static_cast<const Name&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Name::ByteSizeLong() const {
  const Name& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:secure_lab.Name)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // string name = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_name());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Name::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<Name*>(&to_msg);
  auto& from = static_cast<const Name&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:secure_lab.Name)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!from._internal_name().empty()) {
      _this->_internal_set_name(from._internal_name());
    } else {
      if (_this->_impl_.name_.IsDefault()) {
        _this->_internal_set_name("");
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void Name::CopyFrom(const Name& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:secure_lab.Name)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Name::InternalSwap(Name* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
}

::google::protobuf::Metadata Name::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ValidationResponse::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<ValidationResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ValidationResponse, _impl_._has_bits_);
};

ValidationResponse::ValidationResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ValidationResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:secure_lab.ValidationResponse)
}
ValidationResponse::ValidationResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ValidationResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ValidationResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE ValidationResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void ValidationResponse::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.is_valid_ = {};
}
ValidationResponse::~ValidationResponse() {
  // @@protoc_insertion_point(destructor:secure_lab.ValidationResponse)
  SharedDtor(*this);
}
inline void ValidationResponse::SharedDtor(MessageLite& self) {
  ValidationResponse& this_ = static_cast<ValidationResponse&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ValidationResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ValidationResponse(arena);
}
constexpr auto ValidationResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(ValidationResponse),
                                            alignof(ValidationResponse));
}
constexpr auto ValidationResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ValidationResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &ValidationResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ValidationResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ValidationResponse::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ValidationResponse>(), &ValidationResponse::ByteSizeLong,
              &ValidationResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ValidationResponse, _impl_._cached_size_),
          false,
      },
      &ValidationResponse::kDescriptorMethods,
      &descriptor_table_services_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ValidationResponse_class_data_ =
        ValidationResponse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ValidationResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ValidationResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ValidationResponse_class_data_.tc_table);
  return ValidationResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
ValidationResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ValidationResponse, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    ValidationResponse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::secure_lab::ValidationResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool is_valid = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(ValidationResponse, _impl_.is_valid_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(ValidationResponse, _impl_.is_valid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool is_valid = 1;
    {PROTOBUF_FIELD_OFFSET(ValidationResponse, _impl_.is_valid_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void ValidationResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:secure_lab.ValidationResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.is_valid_ = false;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ValidationResponse::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ValidationResponse& this_ = static_cast<const ValidationResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ValidationResponse::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ValidationResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:secure_lab.ValidationResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // bool is_valid = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (this_._internal_is_valid() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          1, this_._internal_is_valid(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:secure_lab.ValidationResponse)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ValidationResponse::ByteSizeLong(const MessageLite& base) {
  const ValidationResponse& this_ = static_cast<const ValidationResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ValidationResponse::ByteSizeLong() const {
  const ValidationResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:secure_lab.ValidationResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // bool is_valid = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (this_._internal_is_valid() != 0) {
        total_size += 2;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ValidationResponse::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<ValidationResponse*>(&to_msg);
  auto& from = static_cast<const ValidationResponse&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:secure_lab.ValidationResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (from._internal_is_valid() != 0) {
      _this->_impl_.is_valid_ = from._impl_.is_valid_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void ValidationResponse::CopyFrom(const ValidationResponse& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:secure_lab.ValidationResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ValidationResponse::InternalSwap(ValidationResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.is_valid_, other->_impl_.is_valid_);
}

::google::protobuf::Metadata ValidationResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class UserPreferences::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<UserPreferences>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(UserPreferences, _impl_._has_bits_);
};

UserPreferences::UserPreferences(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, UserPreferences_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:secure_lab.UserPreferences)
}
PROTOBUF_NDEBUG_INLINE UserPreferences::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::secure_lab::UserPreferences& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        fav_color_(arena, from.fav_color_) {}

UserPreferences::UserPreferences(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const UserPreferences& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, UserPreferences_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  UserPreferences* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.fav_number_ = from._impl_.fav_number_;

  // @@protoc_insertion_point(copy_constructor:secure_lab.UserPreferences)
}
PROTOBUF_NDEBUG_INLINE UserPreferences::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        fav_color_(arena) {}

inline void UserPreferences::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.fav_number_ = {};
}
UserPreferences::~UserPreferences() {
  // @@protoc_insertion_point(destructor:secure_lab.UserPreferences)
  SharedDtor(*this);
}
inline void UserPreferences::SharedDtor(MessageLite& self) {
  UserPreferences& this_ = static_cast<UserPreferences&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.fav_color_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL UserPreferences::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) UserPreferences(arena);
}
constexpr auto UserPreferences::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(UserPreferences),
                                            alignof(UserPreferences));
}
constexpr auto UserPreferences::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_UserPreferences_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &UserPreferences::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<UserPreferences>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &UserPreferences::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<UserPreferences>(), &UserPreferences::ByteSizeLong,
              &UserPreferences::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(UserPreferences, _impl_._cached_size_),
          false,
      },
      &UserPreferences::kDescriptorMethods,
      &descriptor_table_services_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull UserPreferences_class_data_ =
        UserPreferences::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
UserPreferences::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&UserPreferences_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(UserPreferences_class_data_.tc_table);
  return UserPreferences_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 44, 2>
UserPreferences::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(UserPreferences, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    UserPreferences_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::secure_lab::UserPreferences>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 fav_number = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(UserPreferences, _impl_.fav_number_), 1>(),
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(UserPreferences, _impl_.fav_number_)}},
    // string fav_color = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(UserPreferences, _impl_.fav_color_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string fav_color = 1;
    {PROTOBUF_FIELD_OFFSET(UserPreferences, _impl_.fav_color_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 fav_number = 2;
    {PROTOBUF_FIELD_OFFSET(UserPreferences, _impl_.fav_number_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\32\11\0\0\0\0\0\0"
    "secure_lab.UserPreferences"
    "fav_color"
  }},
};
PROTOBUF_NOINLINE void UserPreferences::Clear() {
// @@protoc_insertion_point(message_clear_start:secure_lab.UserPreferences)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.fav_color_.ClearNonDefaultToEmpty();
  }
  _impl_.fav_number_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL UserPreferences::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const UserPreferences& this_ = static_cast<const UserPreferences&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL UserPreferences::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const UserPreferences& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:secure_lab.UserPreferences)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string fav_color = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_fav_color().empty()) {
      const ::std::string& _s = this_._internal_fav_color();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "secure_lab.UserPreferences.fav_color");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // int32 fav_number = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_fav_number() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<2>(
              stream, this_._internal_fav_number(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:secure_lab.UserPreferences)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t UserPreferences::ByteSizeLong(const MessageLite& base) {
  const UserPreferences& this_ = static_cast<const UserPreferences&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t UserPreferences::ByteSizeLong() const {
  const UserPreferences& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:secure_lab.UserPreferences)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // string fav_color = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_fav_color().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_fav_color());
      }
    }
    // int32 fav_number = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_fav_number() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_fav_number());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void UserPreferences::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<UserPreferences*>(&to_msg);
  auto& from = static_cast<const UserPreferences&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:secure_lab.UserPreferences)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_fav_color().empty()) {
        _this->_internal_set_fav_color(from._internal_fav_color());
      } else {
        if (_this->_impl_.fav_color_.IsDefault()) {
          _this->_internal_set_fav_color("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_fav_number() != 0) {
        _this->_impl_.fav_number_ = from._impl_.fav_number_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void UserPreferences::CopyFrom(const UserPreferences& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:secure_lab.UserPreferences)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void UserPreferences::InternalSwap(UserPreferences* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.fav_color_, &other->_impl_.fav_color_, arena);
  swap(_impl_.fav_number_, other->_impl_.fav_number_);
}

::google::protobuf::Metadata UserPreferences::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class UserReport::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<UserReport>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(UserReport, _impl_._has_bits_);
};

UserReport::UserReport(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, UserReport_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:secure_lab.UserReport)
}
PROTOBUF_NDEBUG_INLINE UserReport::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::secure_lab::UserReport& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        fav_color_(arena, from.fav_color_) {}

UserReport::UserReport(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const UserReport& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, UserReport_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  UserReport* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, is_authenticated_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, is_authenticated_),
           offsetof(Impl_, fav_number_) -
               offsetof(Impl_, is_authenticated_) +
               sizeof(Impl_::fav_number_));

  // @@protoc_insertion_point(copy_constructor:secure_lab.UserReport)
}
PROTOBUF_NDEBUG_INLINE UserReport::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        fav_color_(arena) {}

inline void UserReport::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, is_authenticated_),
           0,
           offsetof(Impl_, fav_number_) -
               offsetof(Impl_, is_authenticated_) +
               sizeof(Impl_::fav_number_));
}
UserReport::~UserReport() {
  // @@protoc_insertion_point(destructor:secure_lab.UserReport)
  SharedDtor(*this);
}
inline void UserReport::SharedDtor(MessageLite& self) {
  UserReport& this_ = static_cast<UserReport&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.fav_color_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL UserReport::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) UserReport(arena);
}
constexpr auto UserReport::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(UserReport),
                                            alignof(UserReport));
}
constexpr auto UserReport::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_UserReport_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &UserReport::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<UserReport>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &UserReport::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<UserReport>(), &UserReport::ByteSizeLong,
              &UserReport::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(UserReport, _impl_._cached_size_),
          false,
      },
      &UserReport::kDescriptorMethods,
      &descriptor_table_services_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull UserReport_class_data_ =
        UserReport::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
UserReport::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&UserReport_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(UserReport_class_data_.tc_table);
  return UserReport_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 39, 2>
UserReport::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(UserReport, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    UserReport_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::secure_lab::UserReport>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // bool is_authenticated = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(UserReport, _impl_.is_authenticated_), 1>(),
     {8, 1, 0,
      PROTOBUF_FIELD_OFFSET(UserReport, _impl_.is_authenticated_)}},
    // string fav_color = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(UserReport, _impl_.fav_color_)}},
    // int32 fav_number = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(UserReport, _impl_.fav_number_), 2>(),
     {24, 2, 0,
      PROTOBUF_FIELD_OFFSET(UserReport, _impl_.fav_number_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool is_authenticated = 1;
    {PROTOBUF_FIELD_OFFSET(UserReport, _impl_.is_authenticated_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // string fav_color = 2;
    {PROTOBUF_FIELD_OFFSET(UserReport, _impl_.fav_color_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 fav_number = 3;
    {PROTOBUF_FIELD_OFFSET(UserReport, _impl_.fav_number_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\25\0\11\0\0\0\0\0"
    "secure_lab.UserReport"
    "fav_color"
  }},
};
PROTOBUF_NOINLINE void UserReport::Clear() {
// @@protoc_insertion_point(message_clear_start:secure_lab.UserReport)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.fav_color_.ClearNonDefaultToEmpty();
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000006U)) {
    ::memset(&_impl_.is_authenticated_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.fav_number_) -
        reinterpret_cast<char*>(&_impl_.is_authenticated_)) + sizeof(_impl_.fav_number_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL UserReport::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const UserReport& this_ = static_cast<const UserReport&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL UserReport::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const UserReport& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:secure_lab.UserReport)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // bool is_authenticated = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_is_authenticated() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          1, this_._internal_is_authenticated(), target);
    }
  }

  // string fav_color = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_fav_color().empty()) {
      const ::std::string& _s = this_._internal_fav_color();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "secure_lab.UserReport.fav_color");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // int32 fav_number = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_fav_number() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<3>(
              stream, this_._internal_fav_number(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:secure_lab.UserReport)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t UserReport::ByteSizeLong(const MessageLite& base) {
  const UserReport& this_ = static_cast<const UserReport&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t UserReport::ByteSizeLong() const {
  const UserReport& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:secure_lab.UserReport)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    // string fav_color = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_fav_color().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_fav_color());
      }
    }
    // bool is_authenticated = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_is_authenticated() != 0) {
        total_size += 2;
      }
    }
    // int32 fav_number = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_fav_number() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_fav_number());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void UserReport::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<UserReport*>(&to_msg);
  auto& from = static_cast<const UserReport&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:secure_lab.UserReport)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_fav_color().empty()) {
        _this->_internal_set_fav_color(from._internal_fav_color());
      } else {
        if (_this->_impl_.fav_color_.IsDefault()) {
          _this->_internal_set_fav_color("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_is_authenticated() != 0) {
        _this->_impl_.is_authenticated_ = from._impl_.is_authenticated_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_fav_number() != 0) {
        _this->_impl_.fav_number_ = from._impl_.fav_number_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void UserReport::CopyFrom(const UserReport& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:secure_lab.UserReport)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void UserReport::InternalSwap(UserReport* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.fav_color_, &other->_impl_.fav_color_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(UserReport, _impl_.fav_number_)
      + sizeof(UserReport::_impl_.fav_number_)
      - PROTOBUF_FIELD_OFFSET(UserReport, _impl_.is_authenticated_)>(
          reinterpret_cast<char*>(&_impl_.is_authenticated_),
          reinterpret_cast<char*>(&other->_impl_.is_authenticated_));
}

::google::protobuf::Metadata UserReport::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace secure_lab
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_services_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
