// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: services.proto
#ifndef GRPC_services_2eproto__INCLUDED
#define GRPC_services_2eproto__INCLUDED

#include "services.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace secure_lab {

// define the service (the public facing server)
class Orchestrator final {
 public:
  static constexpr char const* service_full_name() {
    return "secure_lab.Orchestrator";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // define the function
    // what it takes in
    // what it spits out
    virtual ::grpc::Status ExecuteAccessCheck(::grpc::ClientContext* context, const ::secure_lab::Name& request, ::secure_lab::UserReport* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::secure_lab::UserReport>> AsyncExecuteAccessCheck(::grpc::ClientContext* context, const ::secure_lab::Name& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::secure_lab::UserReport>>(AsyncExecuteAccessCheckRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::secure_lab::UserReport>> PrepareAsyncExecuteAccessCheck(::grpc::ClientContext* context, const ::secure_lab::Name& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::secure_lab::UserReport>>(PrepareAsyncExecuteAccessCheckRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // define the function
      // what it takes in
      // what it spits out
      virtual void ExecuteAccessCheck(::grpc::ClientContext* context, const ::secure_lab::Name* request, ::secure_lab::UserReport* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ExecuteAccessCheck(::grpc::ClientContext* context, const ::secure_lab::Name* request, ::secure_lab::UserReport* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::secure_lab::UserReport>* AsyncExecuteAccessCheckRaw(::grpc::ClientContext* context, const ::secure_lab::Name& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::secure_lab::UserReport>* PrepareAsyncExecuteAccessCheckRaw(::grpc::ClientContext* context, const ::secure_lab::Name& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status ExecuteAccessCheck(::grpc::ClientContext* context, const ::secure_lab::Name& request, ::secure_lab::UserReport* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::secure_lab::UserReport>> AsyncExecuteAccessCheck(::grpc::ClientContext* context, const ::secure_lab::Name& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::secure_lab::UserReport>>(AsyncExecuteAccessCheckRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::secure_lab::UserReport>> PrepareAsyncExecuteAccessCheck(::grpc::ClientContext* context, const ::secure_lab::Name& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::secure_lab::UserReport>>(PrepareAsyncExecuteAccessCheckRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void ExecuteAccessCheck(::grpc::ClientContext* context, const ::secure_lab::Name* request, ::secure_lab::UserReport* response, std::function<void(::grpc::Status)>) override;
      void ExecuteAccessCheck(::grpc::ClientContext* context, const ::secure_lab::Name* request, ::secure_lab::UserReport* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::secure_lab::UserReport>* AsyncExecuteAccessCheckRaw(::grpc::ClientContext* context, const ::secure_lab::Name& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::secure_lab::UserReport>* PrepareAsyncExecuteAccessCheckRaw(::grpc::ClientContext* context, const ::secure_lab::Name& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ExecuteAccessCheck_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // define the function
    // what it takes in
    // what it spits out
    virtual ::grpc::Status ExecuteAccessCheck(::grpc::ServerContext* context, const ::secure_lab::Name* request, ::secure_lab::UserReport* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ExecuteAccessCheck : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ExecuteAccessCheck() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ExecuteAccessCheck() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExecuteAccessCheck(::grpc::ServerContext* /*context*/, const ::secure_lab::Name* /*request*/, ::secure_lab::UserReport* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestExecuteAccessCheck(::grpc::ServerContext* context, ::secure_lab::Name* request, ::grpc::ServerAsyncResponseWriter< ::secure_lab::UserReport>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ExecuteAccessCheck<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_ExecuteAccessCheck : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ExecuteAccessCheck() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::secure_lab::Name, ::secure_lab::UserReport>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::secure_lab::Name* request, ::secure_lab::UserReport* response) { return this->ExecuteAccessCheck(context, request, response); }));}
    void SetMessageAllocatorFor_ExecuteAccessCheck(
        ::grpc::MessageAllocator< ::secure_lab::Name, ::secure_lab::UserReport>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::secure_lab::Name, ::secure_lab::UserReport>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ExecuteAccessCheck() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExecuteAccessCheck(::grpc::ServerContext* /*context*/, const ::secure_lab::Name* /*request*/, ::secure_lab::UserReport* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ExecuteAccessCheck(
      ::grpc::CallbackServerContext* /*context*/, const ::secure_lab::Name* /*request*/, ::secure_lab::UserReport* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_ExecuteAccessCheck<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ExecuteAccessCheck : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ExecuteAccessCheck() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ExecuteAccessCheck() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExecuteAccessCheck(::grpc::ServerContext* /*context*/, const ::secure_lab::Name* /*request*/, ::secure_lab::UserReport* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ExecuteAccessCheck : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ExecuteAccessCheck() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ExecuteAccessCheck() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExecuteAccessCheck(::grpc::ServerContext* /*context*/, const ::secure_lab::Name* /*request*/, ::secure_lab::UserReport* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestExecuteAccessCheck(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ExecuteAccessCheck : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ExecuteAccessCheck() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ExecuteAccessCheck(context, request, response); }));
    }
    ~WithRawCallbackMethod_ExecuteAccessCheck() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExecuteAccessCheck(::grpc::ServerContext* /*context*/, const ::secure_lab::Name* /*request*/, ::secure_lab::UserReport* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ExecuteAccessCheck(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ExecuteAccessCheck : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ExecuteAccessCheck() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::secure_lab::Name, ::secure_lab::UserReport>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::secure_lab::Name, ::secure_lab::UserReport>* streamer) {
                       return this->StreamedExecuteAccessCheck(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ExecuteAccessCheck() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ExecuteAccessCheck(::grpc::ServerContext* /*context*/, const ::secure_lab::Name* /*request*/, ::secure_lab::UserReport* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedExecuteAccessCheck(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::secure_lab::Name,::secure_lab::UserReport>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ExecuteAccessCheck<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_ExecuteAccessCheck<Service > StreamedService;
};

// internal service #1 checks the name to see if its in database (private cloud)
class Validator final {
 public:
  static constexpr char const* service_full_name() {
    return "secure_lab.Validator";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status ValidateUser(::grpc::ClientContext* context, const ::secure_lab::Name& request, ::secure_lab::ValidationResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::secure_lab::ValidationResponse>> AsyncValidateUser(::grpc::ClientContext* context, const ::secure_lab::Name& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::secure_lab::ValidationResponse>>(AsyncValidateUserRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::secure_lab::ValidationResponse>> PrepareAsyncValidateUser(::grpc::ClientContext* context, const ::secure_lab::Name& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::secure_lab::ValidationResponse>>(PrepareAsyncValidateUserRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void ValidateUser(::grpc::ClientContext* context, const ::secure_lab::Name* request, ::secure_lab::ValidationResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ValidateUser(::grpc::ClientContext* context, const ::secure_lab::Name* request, ::secure_lab::ValidationResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::secure_lab::ValidationResponse>* AsyncValidateUserRaw(::grpc::ClientContext* context, const ::secure_lab::Name& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::secure_lab::ValidationResponse>* PrepareAsyncValidateUserRaw(::grpc::ClientContext* context, const ::secure_lab::Name& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status ValidateUser(::grpc::ClientContext* context, const ::secure_lab::Name& request, ::secure_lab::ValidationResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::secure_lab::ValidationResponse>> AsyncValidateUser(::grpc::ClientContext* context, const ::secure_lab::Name& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::secure_lab::ValidationResponse>>(AsyncValidateUserRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::secure_lab::ValidationResponse>> PrepareAsyncValidateUser(::grpc::ClientContext* context, const ::secure_lab::Name& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::secure_lab::ValidationResponse>>(PrepareAsyncValidateUserRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void ValidateUser(::grpc::ClientContext* context, const ::secure_lab::Name* request, ::secure_lab::ValidationResponse* response, std::function<void(::grpc::Status)>) override;
      void ValidateUser(::grpc::ClientContext* context, const ::secure_lab::Name* request, ::secure_lab::ValidationResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::secure_lab::ValidationResponse>* AsyncValidateUserRaw(::grpc::ClientContext* context, const ::secure_lab::Name& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::secure_lab::ValidationResponse>* PrepareAsyncValidateUserRaw(::grpc::ClientContext* context, const ::secure_lab::Name& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ValidateUser_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status ValidateUser(::grpc::ServerContext* context, const ::secure_lab::Name* request, ::secure_lab::ValidationResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ValidateUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ValidateUser() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ValidateUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ValidateUser(::grpc::ServerContext* /*context*/, const ::secure_lab::Name* /*request*/, ::secure_lab::ValidationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestValidateUser(::grpc::ServerContext* context, ::secure_lab::Name* request, ::grpc::ServerAsyncResponseWriter< ::secure_lab::ValidationResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ValidateUser<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_ValidateUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ValidateUser() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::secure_lab::Name, ::secure_lab::ValidationResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::secure_lab::Name* request, ::secure_lab::ValidationResponse* response) { return this->ValidateUser(context, request, response); }));}
    void SetMessageAllocatorFor_ValidateUser(
        ::grpc::MessageAllocator< ::secure_lab::Name, ::secure_lab::ValidationResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::secure_lab::Name, ::secure_lab::ValidationResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ValidateUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ValidateUser(::grpc::ServerContext* /*context*/, const ::secure_lab::Name* /*request*/, ::secure_lab::ValidationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ValidateUser(
      ::grpc::CallbackServerContext* /*context*/, const ::secure_lab::Name* /*request*/, ::secure_lab::ValidationResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_ValidateUser<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ValidateUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ValidateUser() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ValidateUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ValidateUser(::grpc::ServerContext* /*context*/, const ::secure_lab::Name* /*request*/, ::secure_lab::ValidationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ValidateUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ValidateUser() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ValidateUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ValidateUser(::grpc::ServerContext* /*context*/, const ::secure_lab::Name* /*request*/, ::secure_lab::ValidationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestValidateUser(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ValidateUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ValidateUser() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ValidateUser(context, request, response); }));
    }
    ~WithRawCallbackMethod_ValidateUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ValidateUser(::grpc::ServerContext* /*context*/, const ::secure_lab::Name* /*request*/, ::secure_lab::ValidationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ValidateUser(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ValidateUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ValidateUser() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::secure_lab::Name, ::secure_lab::ValidationResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::secure_lab::Name, ::secure_lab::ValidationResponse>* streamer) {
                       return this->StreamedValidateUser(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ValidateUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ValidateUser(::grpc::ServerContext* /*context*/, const ::secure_lab::Name* /*request*/, ::secure_lab::ValidationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedValidateUser(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::secure_lab::Name,::secure_lab::ValidationResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ValidateUser<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_ValidateUser<Service > StreamedService;
};

// internal service #2 stores the favorite color and number of the person (private cloud)
class PreferencesService final {
 public:
  static constexpr char const* service_full_name() {
    return "secure_lab.PreferencesService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // returns stats about a user such as favorite color and number
    virtual ::grpc::Status GetUserStats(::grpc::ClientContext* context, const ::secure_lab::Name& request, ::secure_lab::UserPreferences* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::secure_lab::UserPreferences>> AsyncGetUserStats(::grpc::ClientContext* context, const ::secure_lab::Name& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::secure_lab::UserPreferences>>(AsyncGetUserStatsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::secure_lab::UserPreferences>> PrepareAsyncGetUserStats(::grpc::ClientContext* context, const ::secure_lab::Name& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::secure_lab::UserPreferences>>(PrepareAsyncGetUserStatsRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // returns stats about a user such as favorite color and number
      virtual void GetUserStats(::grpc::ClientContext* context, const ::secure_lab::Name* request, ::secure_lab::UserPreferences* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetUserStats(::grpc::ClientContext* context, const ::secure_lab::Name* request, ::secure_lab::UserPreferences* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::secure_lab::UserPreferences>* AsyncGetUserStatsRaw(::grpc::ClientContext* context, const ::secure_lab::Name& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::secure_lab::UserPreferences>* PrepareAsyncGetUserStatsRaw(::grpc::ClientContext* context, const ::secure_lab::Name& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetUserStats(::grpc::ClientContext* context, const ::secure_lab::Name& request, ::secure_lab::UserPreferences* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::secure_lab::UserPreferences>> AsyncGetUserStats(::grpc::ClientContext* context, const ::secure_lab::Name& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::secure_lab::UserPreferences>>(AsyncGetUserStatsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::secure_lab::UserPreferences>> PrepareAsyncGetUserStats(::grpc::ClientContext* context, const ::secure_lab::Name& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::secure_lab::UserPreferences>>(PrepareAsyncGetUserStatsRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetUserStats(::grpc::ClientContext* context, const ::secure_lab::Name* request, ::secure_lab::UserPreferences* response, std::function<void(::grpc::Status)>) override;
      void GetUserStats(::grpc::ClientContext* context, const ::secure_lab::Name* request, ::secure_lab::UserPreferences* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::secure_lab::UserPreferences>* AsyncGetUserStatsRaw(::grpc::ClientContext* context, const ::secure_lab::Name& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::secure_lab::UserPreferences>* PrepareAsyncGetUserStatsRaw(::grpc::ClientContext* context, const ::secure_lab::Name& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetUserStats_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // returns stats about a user such as favorite color and number
    virtual ::grpc::Status GetUserStats(::grpc::ServerContext* context, const ::secure_lab::Name* request, ::secure_lab::UserPreferences* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetUserStats : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetUserStats() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetUserStats() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUserStats(::grpc::ServerContext* /*context*/, const ::secure_lab::Name* /*request*/, ::secure_lab::UserPreferences* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetUserStats(::grpc::ServerContext* context, ::secure_lab::Name* request, ::grpc::ServerAsyncResponseWriter< ::secure_lab::UserPreferences>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetUserStats<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetUserStats : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetUserStats() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::secure_lab::Name, ::secure_lab::UserPreferences>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::secure_lab::Name* request, ::secure_lab::UserPreferences* response) { return this->GetUserStats(context, request, response); }));}
    void SetMessageAllocatorFor_GetUserStats(
        ::grpc::MessageAllocator< ::secure_lab::Name, ::secure_lab::UserPreferences>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::secure_lab::Name, ::secure_lab::UserPreferences>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetUserStats() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUserStats(::grpc::ServerContext* /*context*/, const ::secure_lab::Name* /*request*/, ::secure_lab::UserPreferences* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetUserStats(
      ::grpc::CallbackServerContext* /*context*/, const ::secure_lab::Name* /*request*/, ::secure_lab::UserPreferences* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetUserStats<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetUserStats : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetUserStats() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetUserStats() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUserStats(::grpc::ServerContext* /*context*/, const ::secure_lab::Name* /*request*/, ::secure_lab::UserPreferences* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetUserStats : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetUserStats() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetUserStats() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUserStats(::grpc::ServerContext* /*context*/, const ::secure_lab::Name* /*request*/, ::secure_lab::UserPreferences* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetUserStats(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetUserStats : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetUserStats() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetUserStats(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetUserStats() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUserStats(::grpc::ServerContext* /*context*/, const ::secure_lab::Name* /*request*/, ::secure_lab::UserPreferences* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetUserStats(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetUserStats : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetUserStats() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::secure_lab::Name, ::secure_lab::UserPreferences>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::secure_lab::Name, ::secure_lab::UserPreferences>* streamer) {
                       return this->StreamedGetUserStats(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetUserStats() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetUserStats(::grpc::ServerContext* /*context*/, const ::secure_lab::Name* /*request*/, ::secure_lab::UserPreferences* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetUserStats(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::secure_lab::Name,::secure_lab::UserPreferences>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetUserStats<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetUserStats<Service > StreamedService;
};

}  // namespace secure_lab


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_services_2eproto__INCLUDED
