// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: services.proto

#include "services.pb.h"
#include "services.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace secure_lab {

static const char* Orchestrator_method_names[] = {
  "/secure_lab.Orchestrator/ExecuteAccessCheck",
};

std::unique_ptr< Orchestrator::Stub> Orchestrator::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Orchestrator::Stub> stub(new Orchestrator::Stub(channel, options));
  return stub;
}

Orchestrator::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ExecuteAccessCheck_(Orchestrator_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Orchestrator::Stub::ExecuteAccessCheck(::grpc::ClientContext* context, const ::secure_lab::Name& request, ::secure_lab::UserReport* response) {
  return ::grpc::internal::BlockingUnaryCall< ::secure_lab::Name, ::secure_lab::UserReport, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ExecuteAccessCheck_, context, request, response);
}

void Orchestrator::Stub::async::ExecuteAccessCheck(::grpc::ClientContext* context, const ::secure_lab::Name* request, ::secure_lab::UserReport* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::secure_lab::Name, ::secure_lab::UserReport, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ExecuteAccessCheck_, context, request, response, std::move(f));
}

void Orchestrator::Stub::async::ExecuteAccessCheck(::grpc::ClientContext* context, const ::secure_lab::Name* request, ::secure_lab::UserReport* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ExecuteAccessCheck_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::secure_lab::UserReport>* Orchestrator::Stub::PrepareAsyncExecuteAccessCheckRaw(::grpc::ClientContext* context, const ::secure_lab::Name& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::secure_lab::UserReport, ::secure_lab::Name, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ExecuteAccessCheck_, context, request);
}

::grpc::ClientAsyncResponseReader< ::secure_lab::UserReport>* Orchestrator::Stub::AsyncExecuteAccessCheckRaw(::grpc::ClientContext* context, const ::secure_lab::Name& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncExecuteAccessCheckRaw(context, request, cq);
  result->StartCall();
  return result;
}

Orchestrator::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Orchestrator_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Orchestrator::Service, ::secure_lab::Name, ::secure_lab::UserReport, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Orchestrator::Service* service,
             ::grpc::ServerContext* ctx,
             const ::secure_lab::Name* req,
             ::secure_lab::UserReport* resp) {
               return service->ExecuteAccessCheck(ctx, req, resp);
             }, this)));
}

Orchestrator::Service::~Service() {
}

::grpc::Status Orchestrator::Service::ExecuteAccessCheck(::grpc::ServerContext* context, const ::secure_lab::Name* request, ::secure_lab::UserReport* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* Validator_method_names[] = {
  "/secure_lab.Validator/ValidateUser",
};

std::unique_ptr< Validator::Stub> Validator::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Validator::Stub> stub(new Validator::Stub(channel, options));
  return stub;
}

Validator::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ValidateUser_(Validator_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Validator::Stub::ValidateUser(::grpc::ClientContext* context, const ::secure_lab::Name& request, ::secure_lab::ValidationResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::secure_lab::Name, ::secure_lab::ValidationResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ValidateUser_, context, request, response);
}

void Validator::Stub::async::ValidateUser(::grpc::ClientContext* context, const ::secure_lab::Name* request, ::secure_lab::ValidationResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::secure_lab::Name, ::secure_lab::ValidationResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ValidateUser_, context, request, response, std::move(f));
}

void Validator::Stub::async::ValidateUser(::grpc::ClientContext* context, const ::secure_lab::Name* request, ::secure_lab::ValidationResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ValidateUser_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::secure_lab::ValidationResponse>* Validator::Stub::PrepareAsyncValidateUserRaw(::grpc::ClientContext* context, const ::secure_lab::Name& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::secure_lab::ValidationResponse, ::secure_lab::Name, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ValidateUser_, context, request);
}

::grpc::ClientAsyncResponseReader< ::secure_lab::ValidationResponse>* Validator::Stub::AsyncValidateUserRaw(::grpc::ClientContext* context, const ::secure_lab::Name& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncValidateUserRaw(context, request, cq);
  result->StartCall();
  return result;
}

Validator::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Validator_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Validator::Service, ::secure_lab::Name, ::secure_lab::ValidationResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Validator::Service* service,
             ::grpc::ServerContext* ctx,
             const ::secure_lab::Name* req,
             ::secure_lab::ValidationResponse* resp) {
               return service->ValidateUser(ctx, req, resp);
             }, this)));
}

Validator::Service::~Service() {
}

::grpc::Status Validator::Service::ValidateUser(::grpc::ServerContext* context, const ::secure_lab::Name* request, ::secure_lab::ValidationResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* PreferencesService_method_names[] = {
  "/secure_lab.PreferencesService/GetUserStats",
};

std::unique_ptr< PreferencesService::Stub> PreferencesService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< PreferencesService::Stub> stub(new PreferencesService::Stub(channel, options));
  return stub;
}

PreferencesService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetUserStats_(PreferencesService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status PreferencesService::Stub::GetUserStats(::grpc::ClientContext* context, const ::secure_lab::Name& request, ::secure_lab::UserPreferences* response) {
  return ::grpc::internal::BlockingUnaryCall< ::secure_lab::Name, ::secure_lab::UserPreferences, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetUserStats_, context, request, response);
}

void PreferencesService::Stub::async::GetUserStats(::grpc::ClientContext* context, const ::secure_lab::Name* request, ::secure_lab::UserPreferences* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::secure_lab::Name, ::secure_lab::UserPreferences, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetUserStats_, context, request, response, std::move(f));
}

void PreferencesService::Stub::async::GetUserStats(::grpc::ClientContext* context, const ::secure_lab::Name* request, ::secure_lab::UserPreferences* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetUserStats_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::secure_lab::UserPreferences>* PreferencesService::Stub::PrepareAsyncGetUserStatsRaw(::grpc::ClientContext* context, const ::secure_lab::Name& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::secure_lab::UserPreferences, ::secure_lab::Name, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetUserStats_, context, request);
}

::grpc::ClientAsyncResponseReader< ::secure_lab::UserPreferences>* PreferencesService::Stub::AsyncGetUserStatsRaw(::grpc::ClientContext* context, const ::secure_lab::Name& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetUserStatsRaw(context, request, cq);
  result->StartCall();
  return result;
}

PreferencesService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PreferencesService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PreferencesService::Service, ::secure_lab::Name, ::secure_lab::UserPreferences, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PreferencesService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::secure_lab::Name* req,
             ::secure_lab::UserPreferences* resp) {
               return service->GetUserStats(ctx, req, resp);
             }, this)));
}

PreferencesService::Service::~Service() {
}

::grpc::Status PreferencesService::Service::GetUserStats(::grpc::ServerContext* context, const ::secure_lab::Name* request, ::secure_lab::UserPreferences* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace secure_lab
#include <grpcpp/ports_undef.inc>

